// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBCXgfRr-e9A8RccCb8J9IixCR9I0DExI',
    appId: '1:1015931904993:web:4e4721148101ff206e68a0',
    messagingSenderId: '1015931904993',
    projectId: 'agri-rongeur',
    authDomain: 'agri-rongeur.firebaseapp.com',
    storageBucket: 'agri-rongeur.firebasestorage.app',
    measurementId: 'G-6XMQ8BEPL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0B3mMX6KqILnERPtylro9g-X8VFpY_uk',
    appId: '1:1015931904993:android:9944d0ff3dea84d56e68a0',
    messagingSenderId: '1015931904993',
    projectId: 'agri-rongeur',
    storageBucket: 'agri-rongeur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPvwFu2yESdoMcXk-Qn4K_EqRw7teUMBE',
    appId: '1:1015931904993:ios:3223712bd16a185d6e68a0',
    messagingSenderId: '1015931904993',
    projectId: 'agri-rongeur',
    storageBucket: 'agri-rongeur.firebasestorage.app',
    iosBundleId: 'com.example.agriRongeurMob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPvwFu2yESdoMcXk-Qn4K_EqRw7teUMBE',
    appId: '1:1015931904993:ios:3223712bd16a185d6e68a0',
    messagingSenderId: '1015931904993',
    projectId: 'agri-rongeur',
    storageBucket: 'agri-rongeur.firebasestorage.app',
    iosBundleId: 'com.example.agriRongeurMob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBCXgfRr-e9A8RccCb8J9IixCR9I0DExI',
    appId: '1:1015931904993:web:59d3375c1299840a6e68a0',
    messagingSenderId: '1015931904993',
    projectId: 'agri-rongeur',
    authDomain: 'agri-rongeur.firebaseapp.com',
    storageBucket: 'agri-rongeur.firebasestorage.app',
    measurementId: 'G-W4EK5ZJWCY',
  );
}
